### ISSUE TITLE
Installation fails with "No matching distribution found for google-fhir-core~=0.8"

### ISSUE THREAD

**Issue by jakubadamek** [google/fhir-py#144]
I am using https://colab.sandbox.google.com/ with these lines:

!git clone https://github.com/google/fhir-py.git
!cd fhir-py; ./install_all.sh

This is my output:

Processing ./google-fhir-core
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./google-fhir-r4
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./google-fhir-views
  Preparing metadata (setup.py) ... done
Collecting absl-py~=0.10.0
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
ERROR: Could not find a version that satisfies the requirement google-fhir-core~=0.8 (from google-fhir-views[bigquery,r4]) (from versions: none)
ERROR: No matching distribution found for google-fhir-core~=0.8

**Comment by rbrush** [comment]
Hi, sorry for the slow response. We now have this up on PyPI, so you can install via pip by:

```
pip install google-fhir-views[r4,bigquery]
```

Hope that helps.
