### ISSUE TITLE
compatibility with google-fhir

### ISSUE THREAD

**Issue by Hotrank** [google/fhir-py#304]
Hi, we have a multi language project where we define APIs that depends on [the fhir protos in google-fhir](https://github.com/google/fhir/tree/master/proto/google/fhir/proto). So far we've been able to use the [google-fhir](https://pypi.org/project/google-fhir/) python package for the generated protos.

Now it seems like the google-fhir python package is effectively deprecated and the fhir protos are provided in here (google-fhir-r4, google-fhir-core). However, it also seems like the fhir protos are copied in this repo with a different path, resulting a diffrent import path. And we have a problem when try to deprecate the use of `google-fhir` python package in favor of `google-fhir-r4`, I'll describe the problem below.

In our API proto definition, we have this (we clone the google-fhir repo's protos).
```
import "proto/google/fhir/proto/r4/core/resources/patient.proto";
```
Then, the generated python protobuf files will have
```
from proto.google.fhir.proto.r4.core.resource import patient_pb2
```
which works with the deprecated google-fhir python package.

However, if we want to use the `google-fhir-r4/core` package, it is using this import path (due to it's own folder structure for the protos)
```
from google.fhir.r4.proto.core.resources import patient_pb2
```

Do you have any suggestions on how we can migrate to google-fhir-r4?  We can stay with `google-fhir` package for now but we also want to use the google-fhir-views package for our next project.

**Comment by rbrush** [comment]
Hi Heming,

For some background, the Python package structure in the previous "fhir" project was an artifact of internal structure and bazel-based builds that was unwieldy -- partly with the symptom that both "google" and "proto" show up *twice* in the package name, and it does a poor job of following Python conventions. So we ended up reorganizing the code into a much more Pythonic structure that will (hopefully) be easier to use going forward.

Unfortunately that does mean we needed to change the package location. The protocol buffers in both locations should still be wire-compatible though, so any data you might have persisted or transmitted in protobuf form in the previous code should be readable in the new one. 

Not being familiar with your code base it's hard to give concrete guidance on pulling in an object that was moved to a new location, but if there are components/submodules that could basically do a find/replace to pull in the new protobuf location and apply the change in a single commit, then that might be the best approach to explore.

Apologies for the noise here; we had pushed this as pre-1.0 code so such changes were possible, but now that we have these in a more idiomatic location I think the structure should be stable.

**Comment by Hotrank** [comment]
thank you for your response. I think we will need some way to hack our proto generation to get this working. 

Now a separate question: I see fhirpath is implemented in this package as well, does this package provide a way to  a fhir proto again a fhirpath expression with this package? If so, what's the proper way of doing it?

**Comment by rbrush** [comment]
We have worked on some FHIRPath evaluation logic in Python here, but looking at what has been synced from our internal repo to GitHub, I see that the FHIRPath tests aren't there yet. I'll take a look and see if we can sync the tests to ensure FHIRPath is working properly, which would be a good example of how to use it as well. I'll try to get back to this in the next couple days.

**Comment by rbrush** [comment]
We chatted offline, but for anyone else following along some FHIRPath examples over protocol buffers are here: https://github.com/google/fhir-py/blob/main/google-fhir-r4/README.md#fhirpath-support

**Comment by Hotrank** [comment]
Thanks very much for your help Ryan! Closing this issue now.
